CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_PRODUCT`(
IN_CODIGOBARRA VARCHAR(200),
IN_NOMBRE VARCHAR (120),
IN_ID_CATEGORIA INT,
IN_ID_MARCA INT
)
BEGIN
	INSERT INTO  producto (Codigo_de_Barras, Nombre, Id_Categoria, Id_Marca) VALUES (IN_CODIGOBARRA, IN_NOMBRE, IN_ID_CATEGORIA, IN_ID_MARCA );
END