CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATEPRODUCTO`(
	IN_ID_PRODUCTO INT,
    IN_CODIGOBARRA VARCHAR(200),
	IN_NOMBRE VARCHAR (120),
	IN_ID_CATEGORIA INT,
	IN_ID_MARCA INT

)
BEGIN
UPDATE producto SET Codigo_de_barras = IN_CODIGOBARRA, Nombre = IN_NOMBRE, ID_Categoria = IN_ID_CATEGORIA, Id_Marca = IN_ID_MARCA WHERE Id_Producto =IN_ID_PRODUCTO;
END