CREATE PROCEDURE `UPDATE_PROVIDE` (
	IN RUT INT,
    IN DIGITO_VERIFICADOR INT,
    IN NOMBRES VARCHAR (45),
    IN APELLIDO_P VARCHAR (45),
    IN APELLIDO_M VARCHAR (45),
    IN DIRECCION VARCHAR (45),
    IN RAZON_SOCIAL VARCHAR (45),
    IN NOMBRE_COMERCIAL VARCHAR (45)

)
BEGIN
	UPDATE proveedor SET Rut =  RUT,  Digito_Verificador = DIGITO_VERIFICADOR, Nombres = NOMBRES, Apellido_P = APELLIDO_P, 
    Apellido_M = APELLIDO_M, Direccion = DIRECCION, RAZON_SOCIAL = RAZON_SOCIAL, NOMBRE_COMERCIAL = NOMBRE_COMERCIAL
    WHERE Rut = RUT;
END
