CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_CATEGORY`(
	IN_ID_CATEGORIA int,
    IN_NUEVONOMBRE VARCHAR (120)
)
BEGIN
	UPDATE categoria set Categoria = IN_NUEVONOMBRE WHERE ID_Categoria = IN_ID_CATEGORIA;
END