CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_LOCAL`(
IN_ID INT,
IN_RUT INT,
IN_RAZON_SOCIAL VARCHAR (45),
IN_NOMBRE_COMERCIAL VARCHAR (120))
BEGIN
	UPDATE local SET Rut = IN_RUT, Razon_Social = IN_RAZON_SOCIAL, Nombre_Comercial = IN_NOMBRE_COMERCIAL WHERE Rut = IN_RUT AND Id_Local = IN_ID; 
END